import '../models/facility_model.dart';

class MockFacilities {
  MockFacilities._();

  static List<FacilityModel> get facilities => [
        const FacilityModel(
          id: 'FAC-PUN-001',
          name: 'District Hospital Pune (Aundh)',
          type: 'District Hospital',
          district: 'Pune',
          distanceKm: 12.4,
          etaMinutes: 25,
          totalBeds: 350,
          icuBeds: 24,
          icuAvailable: 4,
          oxygenBeds: 80,
          oxygenAvailable: 18,
          ventilators: 16,
          ventilatorsAvailable: 5,
          specialties: ['Cardiology', 'Emergency Medicine', 'General Surgery', 'Orthopedics', 'Pediatrics'],
          equipment: ['CT Scan', 'Blood Bank', 'Dialysis Unit', 'Cath Lab', '24/7 OT'],
          isAvailable: true,
          address: 'Aundh Camp, Pune, Maharashtra 411027',
          contactNumber: '+91 20 2728 0432',
          latitude: 18.5793,
          longitude: 73.8055,
        ),
        const FacilityModel(
          id: 'FAC-PUN-002',
          name: 'Sassoon General Hospital & BJMC',
          type: 'Government Medical College & Tertiary Hospital',
          district: 'Pune',
          distanceKm: 18.2,
          etaMinutes: 38,
          totalBeds: 1296,
          icuBeds: 90,
          icuAvailable: 8,
          oxygenBeds: 250,
          oxygenAvailable: 45,
          ventilators: 60,
          ventilatorsAvailable: 12,
          specialties: ['Cardiology', 'Neurosurgery', 'Trauma Care', 'Cardiothoracic Surgery', 'Nephrology', 'Burns Unit'],
          equipment: ['128-Slice CT', '3T MRI', 'Biplane Cath Lab', 'Regional Blood Center', 'Trauma Bay ICU'],
          isAvailable: true,
          address: 'Near Pune Railway Station, Pune, Maharashtra 411001',
          contactNumber: '+91 20 2612 8000',
          latitude: 18.5284,
          longitude: 73.8739,
        ),
        const FacilityModel(
          id: 'FAC-PUN-003',
          name: 'Sub-District Hospital Shirur',
          type: 'Sub-District Hospital (SDH)',
          district: 'Pune',
          distanceKm: 6.5,
          etaMinutes: 14,
          totalBeds: 100,
          icuBeds: 8,
          icuAvailable: 2,
          oxygenBeds: 30,
          oxygenAvailable: 7,
          ventilators: 4,
          ventilatorsAvailable: 1,
          specialties: ['General Medicine', 'Obstetrics & Gynecology', 'Pediatrics', 'General Surgery'],
          equipment: ['Digital X-Ray', 'Ultrasound', 'Blood Storage Center', 'Emergency Stabilization'],
          isAvailable: true,
          address: 'Station Road, Shirur, Maharashtra 412210',
          contactNumber: '+91 2137 222045',
          latitude: 18.8262,
          longitude: 74.3776,
        ),
        const FacilityModel(
          id: 'FAC-PUN-004',
          name: 'YCM Hospital Pimpri-Chinchwad',
          type: 'Municipal Medical College & Hospital',
          district: 'Pune',
          distanceKm: 21.0,
          etaMinutes: 42,
          totalBeds: 750,
          icuBeds: 45,
          icuAvailable: 6,
          oxygenBeds: 160,
          oxygenAvailable: 24,
          ventilators: 30,
          ventilatorsAvailable: 7,
          specialties: ['Critical Care', 'Cardiology', 'Pulmonology', 'Polytrauma', 'Dialysis'],
          equipment: ['CT Angiography', 'Cath Lab', 'Level-2 Trauma Bay', 'Component Blood Bank'],
          isAvailable: true,
          address: 'Sant Tukaram Nagar, Pimpri, Pune 411018',
          contactNumber: '+91 20 2742 2222',
          latitude: 18.6279,
          longitude: 73.8131,
        ),
        const FacilityModel(
          id: 'FAC-PUN-005',
          name: 'Sub-District Hospital Baramati',
          type: 'Sub-District Hospital',
          district: 'Pune',
          distanceKm: 48.0,
          etaMinutes: 65,
          totalBeds: 150,
          icuBeds: 12,
          icuAvailable: 0,
          oxygenBeds: 40,
          oxygenAvailable: 3,
          ventilators: 6,
          ventilatorsAvailable: 0,
          specialties: ['General Medicine', 'Pediatrics', 'Obstetrics'],
          equipment: ['Ultrasound', 'X-Ray', 'Emergency Bay'],
          isAvailable: false,
          address: 'Court Road, Baramati, Maharashtra 413102',
          contactNumber: '+91 2112 222340',
          latitude: 18.1517,
          longitude: 74.5772,
        ),
      ];
}
